#!/bin/sh
set -e

if [ -f ./debian/rules ]; then
    [ -f ./debian/changelog ] && debclean -d
    rm -f debian/rules
    echo "-----------------------------------------------------------"
    echo "Running debuild clean and  delete the old debian/rules now."
    echo "Please run bootstrap again!"
    echo ""
    exit 1
fi

if [ -f VERSION ]; then
    . ./VERSION
else
    echo "No VERSION-File, exit!"
    exit 1
fi

# clean up obsolete stuff
rm -f ./debian/install \
      ./debian/ĺinks \
      ./debian/postinst \
      ./debian/postrm  \
      ./debian/prerm \
      ./debian/preinst

[ -d ./debian ] || exit 1


if [ ! -e ./debian/changelog ]; then
    sed -e "s/\@CODENAME\@/${CODENAME}/g" \
        -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
        -e "s/\@VERSION\@/${VERSION}/g" \
        -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
        -e "s/\@DISPLAY\@/${DISPLAY}/g" \
        ../template/debian/changelog \
        > ./debian/changelog
fi


sed -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/debian/control \
    > ./debian/control

sed -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/debian/rules \
    > ./debian/rules
chmod 755 ./debian/rules


rm -f svg/*.svg
for i in ../template/svg/*.svg; do
    BASENAME=$(basename $i)
    sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
        -e "s/\@CODENAME\@/${CODENAME}/g" \
        -e "s/\@VERSION\@/${VERSION}/g" \
        -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
        -e "s/\@DISPLAY\@/${DISPLAY}/g" \
        -e "s/\@REMARK\@/${REMARK}/g" $i \
        > ./svg/${BASENAME}
done

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/debian/install \
    > ./debian/install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/debian/links \
    > ./debian/links

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    -e "s/\@VERSION\@/${VERSION}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ../template/metadata.desktop \
    > ./metadata.desktop

cp ../template/Makefile ./Makefile



echo "-----------------------------------------------------------"
echo "Recreated debian/$foo successful - just go ahead!"
echo ""
