#!/bin/bash
# Copyright 2016 Alf Gaida <agaida@siduction.org>
# License: WTFPL-2

source VERSION

# git checkout templates -- ../$TEMPLATE
# mv ../$TEMPLATE VERSION

rm -rf debtemplate

git checkout templates -- bootstrap
git checkout templates -- debtemplate
git checkout templates -- theme
git checkout templates -- Makefile

[ -f ./debian/rules ] && ./bootstrap && echo "Bootstrap first run ... \n\n"
[ ! -f ./debian/rules ] && ./bootstrap && echo "Bootstrap second run ... \n"

[ -f ./debian/rules ] && rm -rf debtemplate
{ -f ./debian/rules ] && rm -f bootstrap

[ ! -f ./debian/rules ] && echo "Something went wrong, debian/rules not created!  Check bootstrap!"

git add .
