#!/bin/sh
# postinst script for #PACKAGE#

set -e

case "$1" in
    configure)
        if [ -f usr/share/lxqt/themes/whiteroom/lxqt.conf ]; then
            mkdir -p /etc/xdg/lxqt
            cp -a usr/share/lxqt/themes/whiteroom/lxqt.conf /etc/xdg/lxqt
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

