#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        if [ -f /etc/grub.d/05_debian_theme ]; then
            chmod 000 /etc/grub.d/05_debian_theme
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

