#!/bin/sh
# postinst script for siduction-art-rqt-december
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        if [ -f usr/share/razor/themes/december/razor/razor.conf ]; then
            cp -a usr/share/razor/themes/december/razor /etc/xdg/
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

