all:
	for i in dm-kdm lightdm lxqt lxqt-qt5 rqt theme-grub splash-kde splash-xfce wallpaper; \
		do $(MAKE) -C $$i $@; done

clean:
	for i in dm-kdm lightdm lxqt lxqt-qt5 rqt theme-grub splash-kde splash-xfce wallpaper; \
		do $(MAKE) -C $$i $@; done

distclean: clean
