#!/bin/sh
# postinst script for siduction-art-lxqt-thunderstruck
#
# see: dh_installdeb(1)

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    rm -rf /etc/xdg/lxqt/lxqt.conf
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
