all:
	for i in dm-kdm icons splash-kde splash-xfce wallpaper wallpaper2; \
		do $(MAKE) -C $$i $@; done
#  dm-gdm		

clean:
	for i in dm-kdm icons splash-kde splash-xfce wallpaper wallpaper2; \
		do $(MAKE) -C $$i $@; done
# dm-gdm

distclean: clean
