all:
	for i in dm-kdm splash-kde splash-xfce wallpaper wallpaper-2; \
		do $(MAKE) -C $$i $@; done
#  dm-gdm		

clean:
	for i in dm-kdm splash-kde splash-xfce wallpaper wallpaper-2; \
		do $(MAKE) -C $$i $@; done
# dm-gdm

distclean: clean
