all:
	for i in dm-kdm lightdm rqt theme-grub splash-kde splash-xfce wallpaper; \
		do $(MAKE) -C $$i $@; done

clean:
	for i in dm-kdm lightdm rqt theme-grub splash-kde splash-xfce wallpaper; \
		do $(MAKE) -C $$i $@; done

distclean: clean
